### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hadjer25** [HadiNiazi/fullCalendar-js-in-Laravel#1]
this error happened after I finished the 7th video of this project's series 

Uncaught TypeError: Cannot convert undefined or null to object
    at entries (<anonymous>)
    at e (jquery.min.js:4:7727)
    at Ab (jquery.min.js:4:7608)
    at Ab (jquery.min.js:4:7631)
    at Ab (jquery.min.js:4:7631)
    at Function.r.param (jquery.min.js:4:7918)
    at Function.ajax (jquery.min.js:4:12227)
    at Et.e.constructor.select (MyReservations:120:27)
    at constructor.publiclyTrigger (fullcalendar.min.js:9:16482)
    at Et.e.constructor.publiclyTrigger (fullcalendar.min.js:8:30673)

**Comment by HadiNiazi** [comment]
You define your ajax logic without a click event, any way you are watching my video from youtube and reporting on this on my GitHub repo without pulling the code, please mark it as a bug if you pulled my project and it's not working for me you.
